on:
    pull_request:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    automation-tests:
        name: Automation Unit Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set Up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install tox

            - name: Run Tests
              run: tox

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}